name: Deploy Node.js API and Webapp to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Build API
      working-directory: ./api
      run: |
        npm install
        npm run build

    - name: Build Webapp
      working-directory: ./webapp
      run: |
        npm install
        npm run build

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./api/*,./webapp/dist/*"
        target: "/home/ubuntu/deploy"

    - name: SSH and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          pm2 stop all || true
          cp -r ~/deploy/api /home/ubuntu/api
          cd /home/ubuntu/api
          npm install --production
          pm2 start server.js --name api

          rm -rf /var/www/html/webapp
          mkdir -p /var/www/html/webapp
          cp -r ~/deploy/webapp/dist/* /var/www/html/webapp/
          sudo systemctl reload nginx
